spring.application.name=blog-web
spring.datasource.url=jdbc:mysql://localhost:3306/blogweb
spring.datasource.username=root
spring.datasource.password=Tunablink4305@
spring.jpa.hibernate.ddl-auto=update

jwt.secret=mySecretKeyForJwtTokenGenerationAndValidationThatIsLongEnoughForHS512Algorithm!
jwt.expiration-ms=86400000